# Generated by Django 2.2.5 on 2019-09-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='statis',
            new_name='status',
        ),
    ]
